export type FontOption = { value: string; label: string };

export const fontOptions: FontOption[] = [
  { value: "serif", label: "Serif" },
  { value: "sans-serif", label: "Sans" },
  { value: "monospace", label: "Monospace" },
  { value: "Times New Roman", label: "Times New Roman" },
  { value: "Georgia", label: "Georgia" },
  { value: "Garamond", label: "Garamond" },
  { value: "Palatino", label: "Palatino" },
  { value: "Book Antiqua", label: "Book Antiqua" },
  { value: "Cambria", label: "Cambria" },
  { value: "Constantia", label: "Constantia" },
  { value: "Century Schoolbook", label: "Century Schoolbook" },
  { value: "Bookman Old Style", label: "Bookman Old Style" },
  { value: "Arial", label: "Arial" },
  { value: "Helvetica", label: "Helvetica" },
  { value: "Verdana", label: "Verdana" },
  { value: "Tahoma", label: "Tahoma" },
  { value: "Trebuchet MS", label: "Trebuchet MS" },
  { value: "Gill Sans", label: "Gill Sans" },
  { value: "Calibri", label: "Calibri" },
  { value: "Century Gothic", label: "Century Gothic" },
  { value: "Futura", label: "Futura" },
  { value: "Franklin Gothic Medium", label: "Franklin Gothic" },
  { value: "Geneva", label: "Geneva" },
  { value: "Optima", label: "Optima" },
  { value: "Segoe UI", label: "Segoe UI" },
  { value: "Lucida Sans Unicode", label: "Lucida Sans Unicode" },
  { value: "Courier New", label: "Courier New" },
  { value: "Lucida Console", label: "Lucida Console" },
  { value: "Consolas", label: "Consolas" },
  { value: "Roboto", label: "Roboto" },
  { value: "Open Sans", label: "Open Sans" },
  { value: "Lato", label: "Lato" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Poppins", label: "Poppins" },
  { value: "Oswald", label: "Oswald" },
  { value: "Raleway", label: "Raleway" },
  { value: "Nunito", label: "Nunito" },
  { value: "Ubuntu", label: "Ubuntu" },
  { value: "PT Sans", label: "PT Sans" },
  { value: "Mukta", label: "Mukta" },
  { value: "Source Sans 3", label: "Source Sans 3" },
  { value: "Josefin Sans", label: "Josefin Sans" },
  { value: "Quicksand", label: "Quicksand" },
  { value: "Karla", label: "Karla" },
  { value: "Rubik", label: "Rubik" },
  { value: "Titillium Web", label: "Titillium Web" },
  { value: "Fira Sans", label: "Fira Sans" },
  { value: "Noto Sans", label: "Noto Sans" },
  { value: "Inconsolata", label: "Inconsolata" },
  { value: "Source Code Pro", label: "Source Code Pro" },
  { value: "Ubuntu Mono", label: "Ubuntu Mono" },
  { value: "Merriweather", label: "Merriweather" },
  { value: "Playfair Display", label: "Playfair Display" },
  { value: "Lora", label: "Lora" },
  { value: "Noto Serif", label: "Noto Serif" },
  { value: "Crimson Text", label: "Crimson Text" },
  { value: "EB Garamond", label: "EB Garamond" },
  { value: "Cormorant Garamond", label: "Cormorant Garamond" },
  { value: "Spectral", label: "Spectral" },
  { value: "Dancing Script", label: "Dancing Script" },
  { value: "Pacifico", label: "Pacifico" },
  { value: "Great Vibes", label: "Great Vibes" },
  { value: "Bebas Neue", label: "Bebas Neue" },
  { value: "Anton", label: "Anton" },
  { value: "Play", label: "Play" },
  { value: "Righteous", label: "Righteous" },
  { value: "Cinzel", label: "Cinzel" },
];
